name: Build and push
on: [push, workflow_dispatch]

jobs:
  build:
    name: ci-tools
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the git repo
        uses: actions/checkout@v2
      - name: Get ci-tools script
        run: wget --no-cache https://raw.githubusercontent.com/data-be/ci-tools/master/ci.sh
      - name: Make ci-tools runnable
        run: chmod +x ./ci.sh
      - name: Cat ci-tools
        run: cat ./ci.sh
      - name: Run ci-tools
        run: ./ci.sh go --app-name=esutils --dcp-service-name=esutils --docker-username=${{ github.actor }} --docker-password=${{ secrets.GITHUB_TOKEN }} --version-number=$GITHUB_RUN_NUMBER --docker-registry=ghcr.io
